DEVICE_PATH := device/samsung/gta3xlwifi

BOARD_KERNEL_BASE       := 0x10000000
BOARD_KERNEL_PAGESIZE   := 2048
BOARD_KERNEL_IMAGE_NAME := Image
TARGET_PREBUILT_KERNEL  := $(DEVICE_PATH)/prebuilt/$(BOARD_KERNEL_IMAGE_NAME)
TARGET_KERNEL_ARCH      := $(TARGET_ARCH)  # UNUSED HERE

BOARD_INCLUDE_RECOVERY_DTBO       := true
BOARD_PREBUILT_RECOVERY_DTBOIMAGE := $(DEVICE_PATH)/prebuilt/recovery_dtbo

BOARD_BOOT_HEADER_VERSION := 1
BOARD_KERNEL_CMDLINE      += androidboot.selinux=permissive

BOARD_KERNEL_OFFSET        := 0x00008000
BOARD_KERNEL_SECOND_OFFSET := 0xf0000000
BOARD_KERNEL_TAGS_OFFSET   := 0x00000100

BOARD_RAMDISK_OFFSET := 0x01000000

TARGET_BOARD_NAME := SRPSA25A005RU

BOARD_MKBOOTIMG_ARGS += --header_version $(BOARD_BOOT_HEADER_VERSION)
BOARD_MKBOOTIMG_ARGS += --kernel_offset $(BOARD_KERNEL_OFFSET)
BOARD_MKBOOTIMG_ARGS += --second_offset $(BOARD_KERNEL_SECOND_OFFSET)
BOARD_MKBOOTIMG_ARGS += --tags_offset $(BOARD_KERNEL_TAGS_OFFSET)
BOARD_MKBOOTIMG_ARGS += --ramdisk_offset $(BOARD_RAMDISK_OFFSET)
BOARD_MKBOOTIMG_ARGS += --board $(TARGET_BOARD_NAME)
