DEVICE_PATH := device/samsung/gta3xlwifi

TARGET_ARCH         := arm64
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_VARIANT  := cortex-a73
TARGET_CPU_ABI      := arm64-v8a
TARGET_CPU_ABI2     :=

TARGET_2ND_ARCH         := arm
TARGET_2ND_ARCH_VARIANT := $(TARGET_ARCH_VARIANT)
TARGET_2ND_CPU_VARIANT  := cortex-a53
TARGET_2ND_CPU_ABI      := armeabi-v7a
TARGET_2ND_CPU_ABI2     := armeabi

TARGET_USES_64_BIT_BINDER := true  # DEPRECATED
TARGET_BOARD_SUFFIX       := _64   # UNUSED

TARGET_CPU_SMP    := true  # DEPRECATED
ENABLE_CPUSETS    := true  # DEPRECATED
ENABLE_SCHEDBOOST := true  # DEPRECATED/UNUSED?

TARGET_BOARD_PLATFORM        := universal7904
TARGET_BOARD_PLATFORM_GPU    := mali-g71mp2  # UNUSED?
TARGET_BOOTLOADER_BOARD_NAME := exynos7904

BOARD_VENDOR := samsung                          # UNUSED
TARGET_SOC   := $(TARGET_BOOTLOADER_BOARD_NAME)  # UNUSED

TARGET_USES_UEFI := true  # UNUSED

TARGET_NO_BOOTLOADER := true
TARGET_NO_RADIOIMAGE := true

include $(DEVICE_PATH)/BoardConfigBoot.mk

BOARD_HAS_LARGE_FILESYSTEM := true  # DEPRECATED
TARGET_USERIMAGES_USE_EXT4 := true
TARGET_USERIMAGES_USE_F2FS := true

BOARD_FLASH_BLOCK_SIZE := $$(( $(BOARD_KERNEL_PAGESIZE) * 64 ))  # 0x00020000

BOARD_BOOTIMAGE_PARTITION_SIZE     := 0x02000000
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 0x02D00000

BOARD_SYSTEMIMAGE_PARTITION_SIZE   := 0xBE800000
BOARD_USERDATAIMAGE_PARTITION_SIZE := 0x644400000
BOARD_CACHEIMAGE_PARTITION_SIZE    := 0x09800000
BOARD_VENDORIMAGE_PARTITION_SIZE   := 0x14800000
BOARD_PRODUCTIMAGE_PARTITION_SIZE  := 0x13800000

BOARD_SYSTEMIMAGE_FILE_SYSTEM_TYPE   := ext4
BOARD_USERDATAIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_CACHEIMAGE_FILE_SYSTEM_TYPE    := ext4
BOARD_VENDORIMAGE_FILE_SYSTEM_TYPE   := ext4
BOARD_PRODUCTIMAGE_FILE_SYSTEM_TYPE  := ext4

BOARD_BUILD_SYSTEM_ROOT_IMAGE := true
BOARD_ROOT_EXTRA_FOLDERS      := carrier efs omr spu

TARGET_COPY_OUT_VENDOR  := vendor
TARGET_COPY_OUT_PRODUCT := product

BOARD_HAS_NO_SELECT_BUTTON  := true  # DEPRECATED
BOARD_SUPPRESS_SECURE_ERASE := true  # DEPRECATED

include $(DEVICE_PATH)/BoardConfigTWRP.mk
